### ISSUE TITLE
Header examples with comma are displayed incorrectly in curl command

### ISSUE THREAD

**Issue by derklaro** [mrin9/RapiDoc#1063]
When a header is included in the openapi spec and its example contains a comma, the header example is displayed incorrectly in the example curl command. This is especially an issue for date-time headers:
```yaml
      - name: If-Modified-Since
        in: header
        schema:
          format: date-time
          examples:
          - "Wed, 21 Oct 2015 07:28:00 GMT"
```
is displayed as:
![image](https://github.com/user-attachments/assets/2856bf0c-26b3-4cbe-8c43-f0ffe4df6bfa)

this was probably introduced with #1024
