### ISSUE TITLE
Styling for `tab-content` CSS part is not applied

### ISSUE THREAD

**Issue by bandantonio** [mrin9/RapiDoc#1079]
[Documentation](https://rapidocweb.com/css-parts.html):

<img width="456" alt="Image" src="https://github.com/user-attachments/assets/21ce5ecc-1d53-4e03-b333-ad9b3dcd6a4d" />

However, the CSS rule has no effect:

```css
rapi-doc::part(tab-content) {
  background-color: #ffa500;
}
```

<img width="671" alt="Image" src="https://github.com/user-attachments/assets/78d28d4b-3682-483a-8435-c846a3e1cd82" />

All other `tab-*` CSS parts work as expected.
