### ISSUE TITLE
openapi 3.0 server override does not work

### ISSUE THREAD

**Issue by shaigluskin** [mrin9/RapiDoc#130]
Thanks so much for this fantastic api doc renderer!

I'm using openapi 3.0.
I have multiple servers defined as follows:
```
servers:
  - url: https://dev.example.com/v1
  - url: https://qa-example.com/v1
  - url: https://example.com/v1
```
This works as expected, all three servers show in the API Servers section.

However, If I try to [override the default server for a particular method as per this documentation](https://swagger.io/docs/specification/api-host-and-base-path/#overriding) rapi-doc does not recognize it.

```
/some/path:
    get:
      servers:
        - url: https://qa.example.com/v1
```
In the rapi-doc rendering this override is ignored.

Thanks again for all the great work.

**Comment by mrin9** [comment]
That is true, this functionality is missing from RapiDoc, 
This may be something that will take us some time to deliver mostly coz we need to get some business rules into the place since RapiDoc custom-element also allows you to provide server attribute, 
The UI too is designed in a way, where all the server options are applied to whole document

But I will add this into our roadmap.

Thanks for bringing this up

**Comment by shaigluskin** [comment]
Thanks for getting back so quickly.

On a related note, RapiDoc also does not support this OpenAPI 3 pattern:

```
    servers:
      - url: https://{environment}.example.com/v2
        variables:
          environment:
            default: api    # Production server
            enum:
              - api         # Production server
              - api.dev     # Development server
              - api.staging # Staging server
```
For me this is no problem at all; that pattern doesn't really solve a problem for me. But I just thought I'd mention it since I did test it.

When you get to it though, overriding a server choice per method would be great.

**Comment by mrin9** [comment]
I am able to use server-variables with RapiDoc. Have you checked out this example which demonstrate this https://mrin9.github.io/RapiDoc/examples/server-vars.html

the open-api spec for the above example is here https://github.com/mrin9/RapiDoc/blob/master/docs/specs/server.yaml

let me know if you were able to get it working ?

**Comment by shaigluskin** [comment]
I did not succeed at finding a way to _document_ what choices are available to type into the Server Variables form-field. Without that I don't think it is usable. Here is what I did:
```
servers:
  - url: https://{environment}.example.com/v1/alerts
    variables:
      environment:
        description: >
          Server choices:
           * `qa` QA server, is the default.
           * `dev` Development server.
        default: qa
        enum:
          - dev
          - qa
```
Is there a way to get my description info to display?

If not then my fallback pattern is better:
```
servers:
  - url: https://dev.example.com/v1/alerts
  - url: https://qa-example.com/v1/alerts
  - url: https://example.com/v1/alerts
```
Thanks.
