### ISSUE TITLE
Description field for OAS3 Variables

### ISSUE THREAD

**Issue by shaigluskin** [mrin9/RapiDoc#131]
The bolded section below does not display in RapiDoc. 

I have confirmed that putting a description key there is compatible with OAS3. Here is a screenshot of SwaggerUI implementation (Rapi-doc is far superior, just including this as a reference point).
![oas3-environment-variables](https://user-images.githubusercontent.com/611571/74539506-24927000-4f0c-11ea-8655-35aa2d4cdf27.png)

Here is the section from the YAML:
```
servers:
  - url: https://{environment}.example.com/v1/alerts
    variables:
      environment:
        **description: >
          Server choices:
           * `qa` QA server, is the default.
           * `dev` Development server.**
        default: qa
        enum:
          - dev
          - qa
```
So I guess this is a feature request.

Thanks for all the great work on this excellent display formatter for Swagger 2 and OAS 3.
