### ISSUE TITLE
Bug: rendering response example

### ISSUE THREAD

**Issue by maxarndt** [mrin9/RapiDoc#198]
Hey @mrin9!

At first I wanted to thank you for your great work! RapiDoc is pretty much what I was searching for!

I encountered a bug which prevents to render the response example of an API endpoint correctly.

Instead of:
```
[
  {
    fileName: "fileA.txt"
  },
  {
    fileName: "fileB.txt"
  }
],
```

RapiDoc renders:
```
[object Object][object Object]
```

It seems this bug was introduced with release `7.5.0` because if you use the same OpenAPI spec with RapiDoc `7.4.3` there are no problems displaying the response example. The issue still persists with release `8.0.0`.

You can try it with the minimal setup which I pushed to this repo: https://github.com/maxarndt/rapidoc-bug-minimal-demo

**Comment by mrin9** [comment]
thanks for testing it out. this is now addressed (not released), 
To test it for now  pick `rapidoc.min.js` from `dist` folder or generate it from source

**Comment by maxarndt** [comment]
Thanks for your quick response!

Unfortunately, the issue is not finally fixed.

If you have a `string` property with format `date-time` in your arrays object, the example value does not render correctly. It shows up as empty object.

``` 
components:
  schemas:
    Events:
      type: array
      items:
        type: object
        properties:
          fileName:
            type: string
            example: file.txt
          someDate:
            type: string
            format: date-time
      example:
        - fileName: fileA.txt
          someDate: 2017-07-21T17:32:28Z
        - fileName: fileB.txt
          someDate: 2020-04-20T18:11:14Z
``` 

This leads to:
```
[
  {
    fileName: "fileA.txt",
    someDate: { },
  },
  {
    fileName: "fileB.txt",
    someDate: { },
  }
],
```

You can find the updated API spec yaml in my updated repo as well: https://github.com/maxarndt/rapidoc-bug-minimal-demo

I did not test which data types and formats are affected as well of this issue.
