### ISSUE TITLE
UI display in oauth

### ISSUE THREAD

**Issue by winonecheng** [mrin9/RapiDoc#200]
Hi, i try this tool in our api docs in recent days. I think its a great tool including many useful function.

Its our OAS,
```yaml
securitySchemes:
  oAuth2AuthCode:
    type: oauth2
    description: |
      !! its oAuth2AuthCode's description. !!
    flows:
      authorizationCode:
        authorizationUrl: 'https://account.example.com/oauth2/authorize'
        tokenUrl: 'https://account.example.com/oauth2/token'
        refreshUrl: 'https://account.example.com/oauth2/token'
        scopes: {}
  oAuth2ClientCredentials:
    type: oauth2
    description: |
      !! its oAuth2ClientCredentials' description. !!
    flows:
      clientCredentials:
        tokenUrl: 'https://account.example.com/oauth2/token'
        scopes: {}
```
and its corresponding UI

Authentication section:
![image](https://user-images.githubusercontent.com/11289632/80708070-9b0f3900-8b1d-11ea-912e-e8cb8f48b31f.png)

Operation section:
![image](https://user-images.githubusercontent.com/11289632/80708138-bbd78e80-8b1d-11ea-94e4-de262f49fd10.png)

there is some problem:
1. the security scheme name not shown (should be oAuth2AuthCode and oAuth2ClientCredentials)
2. its not easy to identify which oauth flow for an api request to be authorized

If you need more detail, plz let me know 😄

**Comment by mrin9** [comment]
> the security scheme name not shown (should be oAuth2AuthCode and oAuth2ClientCredentials)

 `security scheme name` is an internal name given to the security flows. it is to link the operations with the security flows. It do not add much value in the documentation. People mostly care about which type of flow it is `clientCredentials` or `AuthorizationCode` or something else. If you want to display something special for the flow then provide it in the description. In your case if it is important to display `security scheme name` then put that in the description of the security scheme

> its not easy to identify which oauth flow for an api request to be authorized

If an operation has a security requirements, then it is shown in the top-right corner of that operation. For instance I can see from your screenshot(below) that this operation needs two `oAuth` type of flows. and If need to see what are the two oAuth types, Just hover your mouse on top of the oAuth buttons

![image](https://user-images.githubusercontent.com/11289632/80708138-bbd78e80-8b1d-11ea-94e4-de262f49fd10.png)

In our user-experience survey we found that `security / o-auth` info for each operation isnt that people look for more often, therefore this info is kept in the corner to allow user to focus on the actual content, also it is a repetitive information and showing it prominently for each operation will make the document look un-necessary bulky and long. If you still feel this info should prominently available for each operation, please provide your reasons and i will take them to our UX team

**Comment by winonecheng** [comment]
> and If need to see what are the two oAuth types, Just hover your mouse on top of the oAuth buttons

Its my hover result below

![image](https://user-images.githubusercontent.com/11289632/80781408-c2f5af80-8ba4-11ea-85ce-f58a754b76f9.png)
![image](https://user-images.githubusercontent.com/11289632/80781427-d0ab3500-8ba4-11ea-814f-32ae664b7848.png)

It doesn't show which flow the operation should use.
In my case, there are some api operations use either `clientCredentials` or `AuthorizationCode`, so its better to identify `oAuth` type

**Comment by mrin9** [comment]
I thinks thats a valid point, it isn't that clear from the details. 
Thanks for providing the screenshots, will take them to our UX designer and see how best we can address this

**Comment by winonecheng** [comment]
> If you need to provide one or the other then you must define them in spec

Yes, i define them in all operations. There are two example:

```yaml
/search:
  get:
    security:
      - oAuth2AuthCode: []
      - oAuth2ClientCredentials: []
```
and
```yaml
/me:
  get:
    security:
      - oAuth2AuthCode: []
```

For `/me` operation, user can't know which `oAuth` flow should use, because it just shows security schemes type (`oauth`) instead of name.

Thanks for your kindly reply. Again, RapiDoc is a great API docs solution!
