### ISSUE TITLE
Generate example for nullable and empty string props

### ISSUE THREAD

**Issue by Ivan-Baranov** [mrin9/RapiDoc#211]
In schema (json body)
```yaml
            area:
              type: string
              nullable: true
              example: null
            area_type:
              type: string
              nullable: true
              example: ''
```

In example field:
```
      "area": "string",
      "area_type": "string",
```

Expecting:
```
      "area": null,
      "area_type": "",
```
