### ISSUE TITLE
Verbose response output desired

### ISSUE THREAD

**Issue by shaigluskin** [mrin9/RapiDoc#288]
For the same spec, Swagger produces much more verbose response output. 

Is it possible for Rapidoc to return more robust response information? 

Is something wrong with my [spec](https://app.swaggerhub.com/apis/sgluskin/calendar/1.0.0-oas3#/Calendar%20Day/getCalendarDay) or a Rapidoc setting?

Here is the response header from Rapidoc
```
cache-control: proxy-revalidate
content-type: application/json
```
Here are the response headers from Swagger:

```
Response headers
 access-control-allow-headers: apikeybypass-cacheContent-TypeAcceptX-Requested-WithSession 
 access-control-allow-methods: GETPUTPOSTOPTIONS 
 access-control-allow-origin: * 
 access-control-max-age: 3628800 
 cache-control: no-cache 
 content-encoding: gzip 
 content-length: 83 
 content-type: application/json; charset=utf-8 
 date: Mon24 Aug 2020 19:46:04 GMT 
 etag: W/"53-8bS3imqeCM+qIOAG9lKH80NIBNs" 
 expires: -1 
 proxy-connection: Keep-Alive 
 server: nginx/1.14.0 + Phusion Passenger 5.3.4 
 status: 200200 OK 
 x-powered-by: ExpressPhusion Passenger 5.3.4 
 x-sl-assetpath: /BlahTest/DataManagement/organization/calendar_day 
 x-sl-asseturipath: /api/1/rest/feed-master/queue/BlahTest/DataManagement/organization/calendar_day 
 x-sl-authorized: true 
 x-sl-clientip: 123.45.678.9
 x-sl-pathinfo:  
 x-sl-policyordering: [com-snaplogic-common-jaxrs-apipolicyinterceptor$sessionauthenticatorcom-snaplogic-common-jaxrs-apipolicyinterceptor$snaplogicauthenticatorcom-snaplogic-common-jaxrs-apipolicyinterceptor$authsentinel] 
Request duration
398 ms
```
