### ISSUE TITLE
extra $$ref in responses when using external refs

### ISSUE THREAD

**Issue by ahmadnassri** [mrin9/RapiDoc#290]
###### entrypoint

```yaml
openapi: 3.0.0

paths:
  /:
    get:
      operationId: hello
      description: hello world
      responses:
        $ref: ./responses/index.yml
```

###### `responses/index.yml`

```yaml
200:
  description: successful operation
  content:
    application/json:
      schema:
        type: object
        additionalProperties:
          type: string

404:
  $ref: ../shared/responses/404.yml

401:
  $ref: ../shared/responses/401.yml

5xx:
  $ref: ../shared/responses/5xx.yml
```

result:

![image](https://user-images.githubusercontent.com/183195/91743403-bd759980-eb85-11ea-8398-1d870f74019f.png)

![image](https://user-images.githubusercontent.com/183195/91743462-d5e5b400-eb85-11ea-828e-1e2e81d49f76.png)

note the extra `$$ref`

not sure if i'm doing something wrong, or if a rendering bug
