### ISSUE TITLE
bug / missing functionality: Request and Response Body Examples

### ISSUE THREAD

**Issue by ahmadnassri** [mrin9/RapiDoc#292]
https://swagger.io/docs/specification/adding-examples/#request-response-bodies

when using inline `example` properties it works fine, but when using `$ref` and exposing an example property on the top-level it shows an empty string:

```
content:
  application/json:
    schema:
      $ref: ../../shared/schemas/Error.yml
    example:
      type: https://example.com/probs/out-of-credit
      title: You do not have enough credit.
      detail: Your current balance is 30, but that costs 50.
      instance: "/account/12345/msgs/abc"
      balance: 30
      accounts:
      - "/account/12345"
      - "/account/67890"
```

![image](https://user-images.githubusercontent.com/183195/91775302-b87e0d80-ebb8-11ea-8c99-7d23a953f486.png)
