### ISSUE TITLE
Use names for query string parameter examples

### ISSUE THREAD

**Issue by waldyrious** [mrin9/RapiDoc#295]
The support for query string examples introduced in 9f2fa93 as a fix to #269 seems to use the value of the examples, rather than the name (if they have one, e.g. when using `examples` instead of `example`).

For instance, say I have this parameter:

```yaml
parameters:
  - name: q
    in: query
    description: A search query to filter the returned items
    schema:
      type: string
    examples:
      'Filter by prefix':
        value:
          prefix:foobar
      'Limit number of returned items':
        value:
          limit:20
```

Here's what RapiDoc shows:
<img width="509" alt="Screenshot 2020-09-03 at 11 40 43" src="https://user-images.githubusercontent.com/478237/92105494-d4f99000-edda-11ea-99c6-dfa3c6e86589.png">

And here's what I'd expect to see instead:
<img width="546" alt="Screenshot 2020-09-03 at 11 44 08" src="https://user-images.githubusercontent.com/478237/92105498-d62abd00-edda-11ea-8c4a-f284e0dc9813.png">

(Especially since the content of the example is already shown in the text box, so it's just redundant to show it also in the link label.)

I realize that the examples added in 9f2fa93 use generic names like `example1`, `example2`, etc., but since the `examples` field of OpenAPI parameter objects contains a map, where the keys can be arbitrary strings, it would make sense to assume the names are semantically valid.

**Comment by mrin9** [comment]
> but since the examples field of OpenAPI parameter objects contains a map, where the keys can be arbitrary strings, it would make sense to assume the names are semantically valid.

I dont think that would be a correct assumption to make. 
If the intention is to have an explanation for the example then it should be done using the dedicated `summary` field for this,  using the `keys`

so the above spec can be re-defined as 

```yml
parameters:
  - name: q
    in: query
    description: A search query to filter the returned items
    schema:
      type: string
    examples:
      example1:
        value:
          prefix:foobar
       summary: Filter by prefix
      example2:
        value:
          limit:20
        summary: Limit number of returned items
```
And you should see the desired result

To see it in action checkout the below example
https://mrin9.github.io/RapiDoc/examples/examples-multiple.html#get-/multiple-examples-in-query-param

>(Especially since the content of the example is already shown in the text box, so it's just redundant to show it also in the link label.)

as I explained above we do show the `example-summary` if it exist else fallback on `example-value` however this behavior may change based on user feedbacks we are receiving
- When multiple examples are present we do not show all the values as only one text-box is available, so it wont be redundant to switch to values
- our UX team found that it leads to more confusion as the user needs to find the actual value of the example by clicking on it and watching the textbox. It is also an discoverability issue
- The suggestion from UX is to always show the actual value of example, and upon hovering, show example-summary   
 
I will leave this issue open for a while, if you or others want to add any comments/suggestion
