### ISSUE TITLE
Authentication Basic/Bearer case sensitivity

### ISSUE THREAD

**Issue by dagnelies** [mrin9/RapiDoc#300]
Hi,

I got a definition with following security schemes:

```yaml
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-API-KEY
      in: header
    Basic:
      type: http
      scheme: Basic
    JWT:
      type: http
      scheme: Bearer
    OpenId:
      type: openIdConnect
      openIdConnectUrl: 'https://.../.well-known/openid-configuration'
```

But only the API Key was shown:

![image](https://user-images.githubusercontent.com/5452653/93026667-0b6bb200-f608-11ea-9d69-6a81b4412d4b.png)

...the others are simply blank. For the openIdConnect, I can understand since it's "advanced". However, I was quite taken aback that Basic/Bearer Auth were not working.

After quite some hours, I noticed I mistakenly wrote `Basic` instead of `basic` and `Bearer` instead of `bearer` (which is a bit confusing in the first place IMHO).

It would be nice if this UI (great by the way, thanks!) was a bit more lenient and allow case insensite Basic/Bearer checks. 😃
