### ISSUE TITLE
Description missing for enum properties 

### ISSUE THREAD

**Issue by SteveNay-vz** [mrin9/RapiDoc#335]
My OpenAPI definition contains schemas that include string properties that are enums. The properties have descriptions, but the descriptions are not included in the RapiDoc output. The output only has the word "Allowed" (in bold) and the list of enum values. 

An example property:

```
        applicationClientType:
          description: The category or type of the application client
          type: string
          enum: 
            - Analytics
            - AR
            - ComputerVision
            - Gaming
            - IoT
```
