### ISSUE TITLE
Enum does not render properly

### ISSUE THREAD

**Issue by croudet** [mrin9/RapiDoc#448]
Using  RapiDoc 8.4.9,

with query parameter as follow:
```yaml
- name: "reportType"
        in: "query"
        description: "The type of reports. Default is ALL."
        required: false
        schema:
          type: "string"
          enum:
          - "ALL"
          - "TRANSACTION"
          - "ACCOUNT"
```

when you click any of the enums, the field will display `ALL┃TRANSACTION┃ACCOUNT` instead of the selected enum.
