### ISSUE TITLE
example: null not showing null

### ISSUE THREAD

**Issue by abrari** [mrin9/RapiDoc#477]
RapiDoc version 9.0.0, using `example: null` in API definition does not render null in the example section. For example:

```
  id_reference:
    type: integer
    description: ID reference
    nullable: true
    example: null
```

Shows `0` instead of `null`. I think it is a regression introduced in commit https://github.com/mrin9/RapiDoc/commit/86e9727a44e86cf7e6524a07d03876c46d6e7825. [This line](https://github.com/mrin9/RapiDoc/blob/2ab68d23eb66b7d04605498302546f38cdb0be57/src/utils/schema-utils.js#L125) returns false if `schemaObj.example` is null, so `example` goes undefined and testing it for null does not work as intended.
