### ISSUE TITLE
Issue: array of array of numbers not properly supported

### ISSUE THREAD

**Issue by lequant40** [mrin9/RapiDoc#498]
Hello guys,

I am migrating my API doc from Slatedocs to RapiDoc, and you are doing an amazing work!

Maybe I am missing something, but I think there is an issue with the management of array of array of numbers.

--

First, about the display of the type.

**Reproducer** 
```
assetsPrices:
  type: array
  items:
    type: array
    items:
      type: number
```

In Swagger, this displays properly as:

![image](https://user-images.githubusercontent.com/16731716/121957109-426f1f80-cd62-11eb-9dff-ce26a8f3ea76.png)

But in RapiDoc, the display is showing an empty array of array:

![image](https://user-images.githubusercontent.com/16731716/121957188-5b77d080-cd62-11eb-9ef7-08487a44d51f.png)
![image](https://user-images.githubusercontent.com/16731716/121957291-7f3b1680-cd62-11eb-93f3-7b60238d718f.png)

I would have expected to see [[number]] in the first RapiDoc display mode, and either _array of array of numbers_ or _array of [number]_ in the second RapiDoc display mode.

--

Second, about the description.

**Reproducer** 
```
assetsPrices:
  description: Titi
  type: array
  items:
    description: Toto
    type: array
    items:
      type: number
```

In Swagger, the two descriptions display properly:

![image](https://user-images.githubusercontent.com/16731716/121957532-d17c3780-cd62-11eb-9e9b-62cb2361eced.png)

But in RapidDoc, is seems there is an issue, with only the first description showing:

![image](https://user-images.githubusercontent.com/16731716/121957637-f83a6e00-cd62-11eb-8daa-070d7c46294f.png)

Now, if the first description is removed, the second appears, but is put between weird _array<>_ text:

![image](https://user-images.githubusercontent.com/16731716/121957741-199b5a00-cd63-11eb-97bf-9586ae7c2c20.png)

--

Would it be possible to have your opinion about this behaviour ?

Cheers,

Roman

**Comment by mrin9** [comment]
`Array of array of number` issue is taken care of 
check it out here https://mrin9.github.io/RapiDoc/examples/array-and-object-nesting.html#get-/array-of-array-of-primitive

Regarding description

In RapiDoc to improve nesting readability in schema we combine them in pairs of complex types. What I mean by that is

an array of object is represented as 
```
 [{    <-- collapsing two complex types into single line
   ...
   ...
 }]
``` 
same is for array of array
```
 [[    <-- collapsing two complex types into single line
   ...
   ...
 ]]
``` 
in general it works great. provides a compact view of large schemas. Now since we collapse two complex type into single line 
we can only show one description as showing both description on same line may be confusing. Therefore the way we deal with this is to give priority to the  outer level description if thats missing then use the lower level description


So in the case where we have the below schema
```
assetsPrices:
  description: Outer array description
  type: array
  items:
    description: Inner array description
    type: array
    items:
      type: number
```
- since it has both the description only top description will be shown
- if the top description is missing then below description will be shown (but to indicate that the description belongs to the inner array we use `array<....>` syntax

| Field | Type| Description |
| ----- | -----|------------ |
| assetsPrices |  array of array of number | array &lt; Inner array description &gt;

in general this system works great in most of the cases and was developed by interviewing several users in the past
