### ISSUE TITLE
Issue: Response example description not displayed

### ISSUE THREAD

**Issue by lequant40** [mrin9/RapiDoc#502]
Hello guys,

I think I discovered a bug in the display of Reponse example description.

When there is only one example in an `examples` list of a `reponse`, the associated `description` is not displayed.

Reproducer:

```
              examples:
                Example:
                  description: Computed an arithmetic return of 100% for the first asset and arithmetic returns of respectively 50% and 100% for the second asset
                  value:
                    assets:
                      - assetReturns:
                          - 1
                      - assetReturns:
                          - 0.5
                          - 1
```

This displays right in Swagger:

![image](https://user-images.githubusercontent.com/16731716/122983359-3277c100-d39c-11eb-828c-ad2ada44a4a2.png)

But no description is present in RapiDoc:

![image](https://user-images.githubusercontent.com/16731716/122983405-41f70a00-d39c-11eb-811d-b8b5d9020e48.png)

--
Please note that in case there is only one example in an `examples` list of a `requestBody`, the associated `description` is properly displayed, e.g.

![image](https://user-images.githubusercontent.com/16731716/122983536-6521b980-d39c-11eb-911d-8849cd5783fa.png)

So, I think the issue is only related to `response`.
--

Cheers,

Roman
