### ISSUE TITLE
Example for request does not render correctly for OneOf keyword

### ISSUE THREAD

**Issue by prashantevolvus** [mrin9/RapiDoc#522]
The below **OneOf**  scenario renders correctly in Schema but not in Example. I have checked this scenario in swagger editor and it works fine there as well.
Consider a spec.yaml
```
testoneof:
      type: object
      oneOf:
        - type: object
          properties:
            opt1A:
              type: string
            opt1B:
                type: string
        - type: object
          properties:
            opt2:
              type: string
      properties:
        otherprop1:
          type: string
        otherprop2:
          type: string          
```

Above should show example (JSON) as - 
Example 1
```
{
  otherprop1: " ",
  otherprop2: " ",
  opt1A: " ",
  opt1B: " "
}
```
and 
Example 2
```
{
  otherprop1: " ",
  otherprop2: " ",
  opt2: " "
}
```
Instead it shows 
Example 1
```
{
  opt1A: " ",
  opt1B: " "
}
```
and 
Example 2
```
{
  opt2: " "
}
```
