### ISSUE TITLE
Missing form examples

### ISSUE THREAD

**Issue by majoshi1** [mrin9/RapiDoc#541]
Here are two demos, but one works, while other does not. Any idea?

### Works:
[Fixed form parameters demo 1](https://mrin9.github.io/RapiDoc/examples/dynamic-form-params.html#post-/fixed-form-parameters)
```
                  examples:
                    example1: 
                      summary: Fullname
                      value: Nikola Tesla
                    example2:
                      summary: Name with prefix
                      value: Dr. Albert Einstein
```
![image](https://user-images.githubusercontent.com/292394/130844460-c0cdc314-4844-4f7f-b722-7f4647b809eb.png)

### Does not work:
[Fixed form parameters demo 2](https://jsfiddle.net/Ljz2trmv/2/)

```
          examples:
            example1: 
              summary: Savings
              value: 1123456789
            example2:
              summary: Checking
              value: 2123456789

```

![image](https://user-images.githubusercontent.com/292394/130845014-bfb28d4c-6707-4ec8-a467-1037fe73006f.png)
