### ISSUE TITLE
No input displayed for authentication type cookie

### ISSUE THREAD

**Issue by Raptor399** [mrin9/RapiDoc#548]
First off -- thank you for this amazing project!

API keys of type  `header` seem to be getting form inputs that key of type `cookie` are not.
E.g.

```
    api_key_header:
      description: >
        For this sample, you can use the api key `special-key` to test the
        authorization filters.
      type: apiKey
      name: api_key
      in: header

    api_key_cookie:
      description: >
        For this sample, you can use the api key `special-key` to test the
        authorization filters.
      type: apiKey
      name: api_key
      in: cookie
```

will be shown as: 

![image](https://user-images.githubusercontent.com/879970/132942632-54810e39-51e1-436b-8e18-54e666d894e8.png)

This is not what I would have expected. I would like to be able to edit (and clear when set) cookie API keys, exactly like header API keys.
