### ISSUE TITLE
Bearer token

### ISSUE THREAD

**Issue by Chechotkin** [mrin9/RapiDoc#553]
Last commit (RapiDoc 9.1.1-beta - WebComponent to View OpenAPI docs), I think, breaks Bearer token. It always empty in request: -H "Authorization: Bearer "

**Comment by mrin9** [comment]
It looks like a duplicate of #492 

There has been some recent changes to `9.1.1-beta` to specifically fix this issue which is introduced by release `9.1.0`
However we have now provided a fix in the latest beta so can you once again pickup the latest beta from the dist\rapidoc-min.js  https://raw.githubusercontent.com/mrin9/RapiDoc/master/dist/rapidoc-min.js

and give it a try once more ?

also provide your security scheme setup from spec thats causing this issue (something like below)
```yml
  ...
  securitySchemes:
    http-basic:
      type: http
      scheme: basic
    http-bearer:
      type: http
      scheme: bearer
    api_key1:
      type: apiKey
      name: Authorization
      in: header
    api_key2:
      type: apiKey
      name: specialKey
      in: header
    api_key_cookie:
      description: API Key that should be sent in cookie
        authorization filters.
      type: apiKey
      name: api_key_cookie
      in: cookie
```
