### ISSUE TITLE
Basic and JWT security schemas overrides `Authorization` header

### ISSUE THREAD

**Issue by xSAVIKx** [mrin9/RapiDoc#554]
So we're using the following setup:
1. Username + password ("basic") auth in order to get a JWT token for working with other API methods.
2. We use `JWT` token as "API key" header authentication schema.

```
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
    Authorization:
      type: apiKey
      in: header
      name: Authorization 
paths:
  /cases/auth:
    get:
      security:
        - basic: [ ]
  /cases/doSmth:
    post:
      security:
        - Authorization: [ ]
```

Now what happens, when we use our `auth` endpoint, we use the programmatic API to set the `Authorization` API key. From this moment, we have both `basic` and `apiKey` auth set.

And now if we use the `auth` endpoint again, the JWT token is sent to the endpoint instead of the basic auth.

Just FYI. We have also Swagger UI configured, so it behaves properly in this case. If the schema defines the required security component, only the one noted in the schema is applied.
