### ISSUE TITLE
Array parameter example is incorrectly shown as multiple examples

### ISSUE THREAD

**Issue by NasaGeek** [mrin9/RapiDoc#583]
The following parameter definition:
```
components:
  parameters:
    bounding_box:
      name: bounding_box
      in: query
      schema:
        type: array
        items:
          type: number
        minItems: 4
        maxItems: 4
        example: [40.70066, -97.68181, 30.19397, -74.16356]
```
renders its example unexpectedly
![image](https://user-images.githubusercontent.com/474937/137382885-af65499f-b5fe-4dec-a085-1e1f053e0ec1.png)

It looks like the example is being rendered as 4 possible examples, each being a list of length 1. The intent is for the example to render as a single list of 4 items. My reading of the [OpenAPI docs](https://swagger.io/docs/specification/adding-examples/#:~:text=not%20multiple%20examples.-,Array%20Example,-You%20can%20add) seems consistent with this expectation.

**Comment by mrin9** [comment]
RapiDoc targets OpenAPI 3.1
When provided with a spec written in lower version it tries to upgrade it to 3.1.0 before rendering.  However there are cases where it wont be able to do so, especially in cases where a feature is deprecated.(i,e) it is valid but not preferred

`example` in OpenAPI 3.1.0 is deprecated and replaced with `examples` where you can provide more than one example

will you be able to change your spec to use `examples` instead and provide an array of array instead of just one array ?
 ```yml
components:
  parameters:
    bounding_box:
      name: bounding_box
      in: query
      schema:
        type: array
        items:
          type: number
        minItems: 4
        maxItems: 4
        examples: 
          - [10, 20, 30, 40]
          - [15, 25, 35, 45]
```

let me know if it takes care of your situation
