### ISSUE TITLE
Authentication, security scheme multiple api key error

### ISSUE THREAD

**Issue by iamriel** [mrin9/RapiDoc#589]
First of all, thanks for this awesome project, it works great on my use case until I added multiple api keys for my security scheme.  The library raises the following error:

![image](https://user-images.githubusercontent.com/4214373/138077591-9426ce14-80cf-431b-9a92-26e0499973e0.png)

Below is how the securitySchemes in my yamle file looks

```yaml
  securitySchemes:
    API Key Authentication:
    - type: apiKey
      in: header
      name: X-BUSINESS-ID
      scheme: http
    - type: apiKey
      in: header
      name: X-USER-ID
      scheme: http
```

When there is only one apiKey, it works fine as expected.  I am not sure if it's due to the schema file or to the library itself.

I'm using `/*! RapiDoc 9.1.3`

Thanks!
