### ISSUE TITLE
Using anyOf, how to fix {missing-type-info} ?

### ISSUE THREAD

**Issue by beatcracker** [mrin9/RapiDoc#607]
### Info

I'm trying to upgrade my schema to OpenAPI 3.1.0 and use RapiDoc instead of Swagger UI. What can I do to fix `{missing-type-info}` messages?

**UPD:** Related #254 ?

### Schema

- [openapi.yaml](https://gist.githubusercontent.com/beatcracker/5e78368da361abbd22271b9989f81b35/raw/b5c072d2622b53322eebdf9d45f9d7a32e150142/openapi.yaml)

#### Relevant snippet

```yaml
Path:
  title: Path
  description: >-
    Item path. For environment variables this would be name, for files -
    full path.
  type: object
  additionalProperties: false
  properties:
    linux:
      type: string
      description: This path should be used on Linux.
    macos:
      type: string
      description: This path should be used on macOS.
    windows:
      type: string
      description: This path should be used on Windows.
    default:
      type: string
      description: if no OS-specific path is specified, this one should be used.
  anyOf:
    - required:
        - default
    - required:
        - linux
    - required:
        - macos
    - required:
        - windows
```

### Screenshot

![image](https://user-images.githubusercontent.com/7583050/141694352-c184b45d-0208-4269-a6be-d73e0281a21f.png)
