### ISSUE TITLE
Setting API key programmatically and existing security scheme

### ISSUE THREAD

**Issue by b2p-fred** [mrin9/RapiDoc#683]
My OpenAPI specification defines only one security scheme:
```
components:
  ...
  ...
  securitySchemes:
    eProtocole:
      type: apiKey
      description: 'Send the JWT in the Authorization header.'
      name: Authorization
      in: header
```

In the HTML where I include the `rapid-doc` component, I would like to set the value of my Authorization header. So I wrote something like:
```
    // Configure JWT header - should address 'eProtocole' security scheme, but how-to?
    rapidocEl.setAttribute('api-key-name', 'Authorization');
    rapidocEl.setAttribute('api-key-location', 'header');
    rapidocEl.setAttribute('api-key-value', `Bearer ${token}`);

```

Everything is ok and my API requests include the correct headers but when I am looking at the Authentication sectio nof the doc, I have this:
![image](https://user-images.githubusercontent.com/87375506/157202152-fee45376-9b63-4cab-9e3b-6035d4424eb9.png)

The key applied section appears once my code got executed; else it does not exist. What I would like is to be able to use my defined security scheme and not add a new one. Any solution for this ?
