### ISSUE TITLE
Provide a way to not auto-fill examples for certain parameters

### ISSUE THREAD

**Issue by majoshi1** [mrin9/RapiDoc#686]
We have some optional fields with examples. But, they still getting populated with first value from examples. The default can be set only inside examples. But, that also shows up in examples. So, is it possible to allow setting default outside?
Current: To show empty default for non-required fields.
```
{
	"parameters": [{
			"name": "someName",
			"required": false,
			"schema": {},
			"examples": {
				"default": false,
				"example1": {
					"summary": "Item1",
					"value": "10"
				}
			}
		}
	]
}
```
Proposed: Set default inside schema, so that it does not appear in examples.
```
{
	"parameters": [{
			"name": "someName",
			"required": false,
			"schema": {
				"default": false
			},				
			"examples": {
				"example1": {
					"summary": "Item1",
					"value": "10"
				}
			}
		}
	]
}
```

**Comment by mrin9** [comment]
I am not sure whats the ask here. Can you explain with some screen shot may be, what are you getting and what do you intent to have

**Comment by majoshi1** [comment]
Sorry for any confusion. This is actually a defect that optional fields are pre-populated with first value from examples. Can provide example if needed.

**Comment by hrvoj3e** [comment]
I have the same problem.

I would like to somehow hint in yaml schema that field should not be populated from example.

```yaml
get:
  summary: content search
  operationId: seachContent
  tags:
    - content-search
  parameters:
    - in: query
      name: search
      examples:
        a:
          value: my example 1
        b:
          value: "*"
      schema:
        type: string
      description: term to search (use "*" to show all)
    - in: query
      name: id
      example: my-id
      schema:
        type: string
    - in: query
      name: db
      example: ccc
      schema:
        type: string
        enum:
         - aaa
         - bbb
         - ccc
         - ddd
  responses:
    200:
      description: OK
      content:
        application/json: {}
    400:
      $ref: "../response/400.yaml"
```


![image](https://user-images.githubusercontent.com/4988133/158413436-415a3ecc-1ef7-4605-8e7f-09f1e500305b.png)

**Comment by mrin9** [comment]
> Maybe some extension field x-example-fill: false or something?

I think thats a good suggestion. 
added to our queue

**Comment by mrin9** [comment]
use vendor extension `x-example-fill : no`  for each parameter to indicate if it should be filled
you may also use RapiDoc attribute `fill-request-fields-with-example = true/false` to indicate no autofilling of example for the entire spec

```yml
get:
  summary: content search
  operationId: seachContent
  tags:
    - content-search
  parameters:
    - in: query
      name: search
      example: 'my-search-string'
      x-fill-example:  no.     # <--- vendor extension
      schema:
        type: string
      description: term to search (use "*" to show all)
    - in: query
      name: id
      example: my-id
      schema:
        type: string
```
