### ISSUE TITLE
No visual indication for a deprecated parameter

### ISSUE THREAD

**Issue by b2p-fred** [mrin9/RapiDoc#687]
In my specification:
```
  /api/documents:
    get:
      parameters:
        -
          name: type
          in: query
          description: 'Set this value to filter on the document history type'
          required: false
          deprecated: true
          allowEmptyValue: true
          schema:
            type: string
            enum:
              - sent
              - validated
              - declined
              - abandoned
              - archived
            default: sent
          style: form
          explode: false
          allowReserved: false
          example: sent
        -
          name: documentType
          in: query
          description: 'Set this value to filter on the document history type'
          required: false
          deprecated: false
          allowEmptyValue: true
          schema:
            type: string
            enum:
              - sent
              - validated
              - declined
              - abandoned
              - archived
            default: sent
          style: form
          explode: false
          allowReserved: false
          example: sent

```

On the UI:
![image](https://user-images.githubusercontent.com/87375506/157384868-34f76eeb-5a01-4744-8435-7b0e40c0eff8.png)

I expected to have a visual indication or a message that indicates that the `type` field is now deprecated. I know there is such a visual indication (line through) in the request body parameters :wink:
