### ISSUE TITLE
Seems RapiDoc is not respecting `explode: false`

### ISSUE THREAD

**Issue by Cowboy-coder** [mrin9/RapiDoc#69]
If I set this in my openapi specification
```yaml
parameters:
- name: id
  in: query
  description: Comma seperated ids
  style: form
  explode: false
  schema:
    type: array
    items:
      type: string
```
I expect RapiDoc to send ids separated by comma like this: `?id=x,y,z`

Right now RapiDoc sends: `?id=x&id=y&id=z` instead.

Cool project!
