### ISSUE TITLE
posibility to not auto populate examples in parameters

### ISSUE THREAD

**Issue by hrvoj3e** [mrin9/RapiDoc#698]
See my comment [here](https://github.com/mrin9/RapiDoc/issues/686#issuecomment-1068126181) (ne reason to duplicate it here).

My current "fix" is to use `examples` with first example having empty value.
```yaml
parameters:
  - in: query
    name: with
    schema:
    type: string
    examples:
      a:
        value: ## this has no value - so it will not be auto populated and sent with request
      b:
        value: file-info
        summary: show file info
```

I used this but I often find myself manually clearing all examples or a few of them so I could run the request without them.
```yaml
parameters:
  - in: query
    name: with
    schema:
      type: string
      example: file-info
```

It would be useful to add a clear button for each field (`in: query` or `in: param`).
