### ISSUE TITLE
rapi-doc-mini - setApiKey not working

### ISSUE THREAD

**Issue by hrvoj3e** [mrin9/RapiDoc#707]
Hi. I have a required authentication via token.
`setApiKey` works with `rapi-doc` but not with `rapi-doc-mini`.

https://mrin9.github.io/RapiDoc/rapidoc-mini.html

Is this intended like that or is it a bug?

```html
<script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>

<rapi-doc-mini match-paths="get /catalog($|/collection)$" match-type="regex" spec-url="http://local.net:8007/oas-api/ui2/api-spec/root.yaml" theme="light" paths-expanded="false" id="docs"> </rapi-doc-mini>

<script>
window.onload = (event) => {
    document.getElementById("docs").addEventListener('spec-loaded', (e) => {
        document.getElementById("docs").setApiKey('api-token', '10006|4Yd1F7AdUaFP2xxxxxxxoNXl5VZT0pNZHoh2Auk');
    });
};
</script>
```

```yaml
# global security enabled
security:
  - api-token: []
components:
  securitySchemes:
    api-token:
      type: http
      scheme: bearer
      description: my token
```

```
Uncaught TypeError: document.getElementById(...).setApiKey is not a function
    at ne.afterSpecParsedAndValidated (rapidoc-mini.js:130:1)
```
