### ISSUE TITLE
feature request - examples extension

### ISSUE THREAD

**Issue by hrvoj3e** [mrin9/RapiDoc#708]
Voting for option to **opt-in** showing summary or keys or both.
Maybe is ugly for default usage but for specific use cases it is really helpful.

Here is an example

```yaml
in: query
name: id
schema:
  type: integer
  format: int32
  minimum: 10000
examples:
  empty: ## just an empty value ## fixes auto filling example
    value:
  demo-1:
    value: 10101
  canceled-order:
    value: 10102
  order-with-discount:
    value: 10103
  order-with-discount-2:
    value: 10104
    summary: there are multiple discount applied

x-examples-summary-show: title
x-examples-key-show: true
```

Showing `10101 | 10102 | 10103 | 10104` to user is not helpful.
But showing `demo-1 | canceled-order | order-with-discount | order-with-discount` is useful and clear what that example will show.

Also, if you could find some place to display `summary` after user clicks on one example - that would be great.

```yaml
x-examples-key-show: true
x-examples-summary-show: selected # when seelcted only
# or
x-examples-summary-show: title # show on hover (this should be default: true)
```

Example - swagger
 - they show dropdown
 - it is "ok" but only sometimes
   - again - as an opt-in option - sure
 - https://swagger.io/docs/specification/adding-examples/
   - [view above example in their online editor](https://editor.swagger.io/?url=https://gist.githubusercontent.com/hrvoj3e/f24b12a7aab8486a6a59f095bcc7edc6/raw/162b85d975348febac73355169b747beed3ab606/oas-param-examples.yaml)

Also there is similar [request](https://github.com/mrin9/RapiDoc/issues/685)
