### ISSUE TITLE
Recursion error when models are spread across multiple files (Maximum call stack size exceeded)

### ISSUE THREAD

**Issue by elnipa** [mrin9/RapiDoc#711]
I got a recursion in my model which worked fine in ReDoc. In RapiDoc it will raise js error.

```
common-utils.js:13 RangeError: Maximum call stack size exceeded
    at T.dispatchException (common-utils.js:13:1)
    at Generator._invoke (common-utils.js:13:1)
    at Generator.next (common-utils.js:13:1)
    at p (common-utils.js:13:1)
    at A (common-utils.js:13:1)
    at Generator._invoke (common-utils.js:13:1)
    at Generator.next (common-utils.js:13:1)
    at p (common-utils.js:13:1)
    at A (common-utils.js:13:1)
    at Generator._invoke (common-utils.js:13:1)
```

### transformation-node.model

```yaml
title: Transformation Node
anyOf:
  - $ref: ./nodes/transformation-node_addition.model.yaml
  - $ref: ./nodes/transformation-node_constant.model.yaml
  - $ref: ./nodes/transformation-node_division.model.yaml
  - $ref: ./nodes/transformation-node_multiplication.model.yaml
  - $ref: ./nodes/transformation-node_subtraction.model.yaml
```

### ./nodes/transformation-node_addition.model.yaml
```yaml
title: Addition
type: object
description: Transformation node for a addition operation (summand1 + summand2)
properties:
  type:
    type: string
    description: Type of transformation expression
    enum:
      - ADDITION
    example: ADDITION
  parameter1:
    type: object
    description: First summand
    $ref: ../transformation-node.model.yaml
  parameter2:
    type: object
    description: Second summand
    $ref: ../transformation-node.model.yaml

```
