### ISSUE TITLE
Unexpected result when using OpenAPI server templating

### ISSUE THREAD

**Issue by mikemadisonweb** [mrin9/RapiDoc#88]
Seems like OpenAPI server templating is not supported?
Server part of the specification:
```
servers:
  - url: '{schema}://domain-from-spec.com/{basePath}'
    variables:
      basePath:
        enum:
          - v1
        default: v1
      schema:
        enum:
          - http
        default: http
```
Expected:
http://domain-from-spec.com/v1
Actual:
https://ui-domain.com{schema}://domain-from-spec.com/{basePath}

Are there any plans to implement server templating support?
